### ISSUE TITLE
Is this something that could help with CrewLink cross-platform support? 

### ISSUE THREAD

**Issue by jasikpark** [TauAkiou/amonguscapture-gtk#8]
https://github.com/ottomated/CrewLink/issues/4

I've got no clue, but it'd be nice

**Comment by TauAkiou** [comment]
It would be possible to port the changes made in CrewLink and build your own communication interface with the CrewLink server. The end result would be a C# CrewLink client that works the same way, and since it uses the C# memory toolkit, any incompatibilities with memoryjs wouldn't be present.

Granted, this would require a bit of porting, changes to the memory reading code and a custom rework of the GUI (as necessary).

**Comment by TauAkiou** [comment]
Additionally, if the CrewLink client is what is handling the audio, you would have to implement the audio output stream using C++ by hand. This is due to the lack of C# bindings for PulseAudio.

**Comment by jasikpark** [comment]
https://github.com/ottomated/CrewLink/blob/master/src/renderer/Voice.tsx 

It looks like the client is editing the audio via native html audio ~ so I would feel like trying to drop amongus-capture in as a memoryjs replacement would work simplest, no? Since that sounds like the only incompatibility ~ memoryjs is solely windows oriented

**Comment by TauAkiou** [comment]
Closed, as this issue is out of scope for this project.
